[package]
name = "reth-firehose-tracer"
version = "0.1.0"
edition = "2024"

[dependencies]
reth = { path = "../reth/bin/reth" }                           # git = "https://github.com/paradigmxyz/reth.git" }
reth-exex = { path = "../reth/crates/exex/exex" }              # git = "https://github.com/paradigmxyz/reth.git" }
reth-node-ethereum = { path = "../reth/crates/ethereum/node" } # git = "https://github.com/paradigmxyz/reth.git" }
reth-tracing = { path = "../reth/crates/tracing" }             # git = "https://github.com/paradigmxyz/reth.git" }
reth-cli-util = { path = "../reth/crates/cli/util" }           # git = "https://github.com/paradigmxyz/reth.git" }

alloy-genesis = "1"
alloy-primitives = "1.3"
alloy-consensus = "1"
alloy-rlp = "0.3"
base64 = "0.22"
clap = "4"
eyre = "0.6"
futures-util = "0.3"
hex = "0.4"
prost = "0.14"
prost-types = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# reth-exex = { path = "../reth/crates/exex/exex" }
# reth-node-ethereum = { path = "../reth/crates/ethereum/node" }
# reth-tracing = { path = "../reth/crates/tracing" }
